(in-package :pl1.tests)
(defparameter empty-string "")
(defparameter simple-prog "p:proc;end;")
(fiveam:def-test main ()
  (let ((program)
        )
    (setf program (make-program empty-string))
    (is (= 0 (length (children program))))
    (is (equalp empty-string (source program)))
    (is (= 0 (length (statements program))))
    (setf program (make-program simple-prog))
    (is (equalp simple-prog (source program)))
    (is (= 2 (length (statements program))))
    (let ((procs (children program)))
      (is (= 1 (length procs)))
      (is-true (gethash :p (symbol-table program)))
      )
    )
  )
